version: '2'

services:
  wireguard:
    image: linuxserver/wireguard
    container_name: wireguard
    hostname: iobroker
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    volumes:
      - ./vpn_config:/config
      - /lib/module:/lib/modules
    ports:
      - 8081:8081
      - 8087:8087
      - 1883:1883
      - 8084:8084
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
    restart: unless-stopped
    
  iobroker:
    image: buanet/iobroker
    container_name: iobroker
    volumes:
      - ./iobrokerdata:/opt/iobroker
      - ./startup:/opt/userscripts
    depends_on:
      - wireguard
    network_mode: service:wireguard
    restart: always
