version: '2'

services:
  wireguard:
    build:
      context: ./wireguard
    container_name: wireguard
    hostname: iobroker
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    volumes:
      - ./vpn_config:/config
      - /lib/module:/lib/modules
      - ./logs:/logs
    ports:
      - 8081:8081 # Adapter: Admin
      - 8087:8087 # Adapter: REST-API
      - 1883:1883 # Adapter: MQTT
      - 8883:8883 # Adapter: MQTT (TLS) - Not implemented
      - 8084:8084 # Adapter: Socket.io
      - 16021:16021/tcp # Adapter: Nanoleaf
      - 1900:1900/udp # Adapter: Nanoleaf (Alive-Check)
      - 5000:5000/udp # Adapter: Nanoleaf (Search device)
      - 8082:8082 # Adapter: Web
      - 3000:3000 # Wireshark: Access via http
      - 3001:3001 # Wireshark: Access via https
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
    restart: unless-stopped
  iobroker:
    image: buanet/iobroker
    container_name: iobroker
    restart: always
    volumes:
      - ./iobrokerdata:/opt/iobroker
      - ./startup:/opt/userscripts
    depends_on:
      - wireguard
    network_mode: service:wireguard

  wireshark:
    image: lscr.io/linuxserver/wireshark:latest
    container_name: wireshark
    cap_add:
      - NET_ADMIN
    security_opt:
      - seccomp:unconfined #optional
    depends_on:
      - wireguard
    network_mode: service:wireguard
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - CUSTOM_USER=admin
      - PASSWORD=SecuredSmartHome23
    volumes:
      - /path/to/config:/config
      - ./logs:/logs
    restart: unless-stopped

  inotify:
    build:
      context: ./inotify
    container_name: inotify
    environment:
      - VOLUMES=/iobroker
      - WATCH_DIFFERENCES=/iobroker/iobroker-data/states.jsonl /iobroker/iobroker-data/objects.jsonl
    volumes:
      - ./iobrokerdata:/iobroker
      - ./logs:/logs
    restart: unless-stopped

  tshark:
    build:
      context: ./tshark
    container_name: tshark
    depends_on:
      - wireguard
    environment:
      - TSHARK_DURATION=3600
      - TSHARK_FILES=24
      - TSHARK_ETH0_FILTER=udp port 51820
    network_mode: service:wireguard
    volumes:
      - ./logs:/logs
    restart: unless-stopped